### ISSUE TITLE
Regression: GOG games do not launch

### ISSUE THREAD

**Issue by mcphail** [ubuntu-mate/mate-menu#75]
Since commit 6e9dce4d9081158dc3b06324d374be26ad7f8247 was released in the 20.04.2-0ubuntu1 deb, mate-menu no longer launches my GOG games. I haven't been able to debug why this is the case, but think it might be related to the second parameter in the `Exec=` line of these `.desktop` files which call the GOG launcher scripts. An example `.desktop` is:
```
[Desktop Entry]
Encoding=UTF-8
Value=1.0
Type=Application
Name=Streets of Rogue
GenericName=Streets of Rogue
Comment=Streets of Rogue
Icon=/home/neil/GOG Games/Streets of Rogue/support/icon.png
Exec="/home/neil/GOG Games/Streets of Rogue/start.sh" ""
Categories=Game;
Path=/home/neil/GOG Games/Streets of Rogue
```

This launches perfectly fine from the brisk-menu and worked with the previous versions of mate-menu.

**Comment by diddledan** [comment]
line 39 looks suspicious: https://github.com/ubuntu-mate/mate-menu/commit/6e9dce4d9081158dc3b06324d374be26ad7f8247#diff-d060b4748f5e96298c82d0199d3bb07dR39

**Comment by flexiondotorg** [comment]
@vkareh Please, can you take a look at this one?

**Comment by vkareh** [comment]
Sent in a patch (#76). The issue is the `Path` in that Desktop Entry, which we weren't correctly taking into account. I'm pretty sure this patch should fix it, based on my tests.

**Comment by mcphail** [comment]
I don't really know how to build and test this myself. If anyone is able to roll me a .deb I'd be happy to feed back!

**Comment by drws** [comment]
Unfortunately this is **not completely solved** since the latest patch introduced another more or less critical bug. While the latest version allows for a proper launching of certain applications, it unfortunately changes the mate-menu's execution context for **every application** until another launcher containing `Path=` is used (and majority of them don't have it).

This can be easily demonstrated by launching an application with a desktop launcher containing `Path=` directive from `mate-menu` first and launching `mate-terminal` from `mate-menu` afterwards. It starts in path of the first launcher.

A better way to change working directory only for the spawned process probably needs to be implemented. Executing the launched application in a subshell comes to mind: `(cd $PATH && command)` and removing the `os.chdir()` call of the execution environment.

I believe this report should be reopened or if necessary I can also write another.
